image: Visual Studio 2017

environment:
  PYTHON: C:\Python34-x64
  
install:
  - git submodule update --init --recursive

build_script:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python --version
  - python build.py
  
artifacts:
  - path: build\x64\Release\*.dll
    name: DLL only
  - path: build\*.zip
    name: Packaged
