image: Visual Studio 2017

environment:
  PYTHON: C:\Python34-x64

build_script:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python --version
  - python build.py
  
artifacts:
  - path: build\x64\Release\mcm.dll
    name: MCM